// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef sharme_ui_h
#define sharme_ui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Round_Button.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Value_Slider.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Return_Button.H>

class SharmeUI {
public:
  int state; 
  SharmeUI();
  Fl_Double_Window *sharme_window;
  Fl_Box *lb_header;
  Fl_Box *status_led;
  Fl_Box *status_label;
  Fl_Group *gr_mode;
  Fl_Round_Button *rb_manage;
  Fl_Round_Button *rb_share;
  Fl_Group *gr_props;
  Fl_Input *te_server;
  Fl_Value_Slider *sl_quality;
  Fl_Input *te_keycode;
  Fl_Button *bt_exit;
  Fl_Return_Button *bt_start;
  void show(int argc, char **argv);
  void disconnected();
  void connected();
  void ready();
  void connecting();
};
#endif
